config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "likes/:image_id", to: "likes#create", as: :likes
  delete "likes/:image_id", to: "likes#destroy", as: :like
  post "favorites/:image_id", to: "favorites#create", as: :favorites
  delete "favorites/:image_id", to: "favorites#destroy", as: :favorite

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure

  resources :users do
    member do
      get :favorite
      get :following
      get :followers
    end
    collection do
      post :notification
      get :search
    end
  end
  resources :password_change, only: [:edit, :update]
  resources :images, only: [:new, :show, :create, :destroy] do
    collection do
      post :preview
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :facebook_login, only: [:edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end
end

app/views/static_pages/_feed.html.haml
.feed-area
  %ol
    - @user.feed.each do |image|
      %li
        .feed-header
          = link_to user_path(image.user) do
            = render "shared/user_avatar", {user: image.user, size: 40}
          %p= image.user.user_name
        = image_tag image.post_image.variant(resize_to_fill: [600, 600]).processed, alt: "投稿された画像"
        .feed-icon-area
          .like-button{ id: "like-button-#{image.id}" }
            = render "shared/like_button", image: image
          = link_to image_path(image), class: "image-show-link" do
            %i.far.fa-comment
          .favorite-button.feed-favorite{ id: "favorite-button-#{image.id}" }
            = render "shared/favorite_button", image: image
        %p.likes-count{ id: "likes-count-#{image.id}" }= "#{image.likes.count}人が「いいね！」しました"
        .feed-comment-show-area{ id: "feed-image-#{image.id}" }
          = render "shared/feed_comments", {comments: image.posted_comments, avatar_appear: false}
        .feed-comment-area
          = form_with model: image.comments.build, remote: true, class: "input-group" do |f|
            = f.text_area :comment, class: "post-comment-area", placeholder: "コメントを追加…", rows: "1", id: "comment-#{image.id}"
            = f.hidden_field :image_id, value: image.id
            = f.hidden_field :user_id, value: current_user.id
            = f.hidden_field :state, value: "home"
            .input-group-append
              = f.submit "投稿する", class: "btn"

app/views/static_pages/_login_form.html.haml
.login_form
  .wrapper
    %h1 InstaClone
    = form_with url: login_path, local: true do |f|
      = f.email_field :email, placeholder: "メールアドレス", class: "form-control"
      = f.password_field :password, placeholder: "パスワード", class: "form-control"

      = f.submit "ログインする", class: "btn btn-primary"
    = link_to "Facebookでログイン", "auth/facebook"
.create_user_link
  - signup_link = link_to "登録する", signup_path
  %p アカウントをお持ちでないですか？#{signup_link}

app/views/static_pages/_user_info.html.haml
.user-info-area
  = link_to user_path(@user) do
    = render "shared/user_avatar", {user: @user, size: 70}
  .user-info-name
    %p.user-info-user-name= @user.user_name
    %p.user-info-full-name= @user.full_name

app/views/static_pages/home.html.haml
- if logged_in?
  - @header_appear = true
- @footer_appear = true
.home
  - if logged_in?
    .user-home-page
      .container
        .row.justify-content-md-center
          .col
            = render "static_pages/feed"
          .col
            = render "static_pages/user_info"
  - else
    = render "static_pages/login_form"