config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "likes/:image_id", to: "likes#create", as: :likes
  delete "likes/:image_id", to: "likes#destroy", as: :like
  post "favorites/:image_id", to: "favorites#create", as: :favorites
  delete "favorites/:image_id", to: "favorites#destroy", as: :favorite

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure

  resources :users do
    member do
      get :favorite
      get :following
      get :followers
    end
    collection do
      post :notification
      get :search
    end
  end
  resources :password_change, only: [:edit, :update]
  resources :images, only: [:new, :show, :create, :destroy] do
    collection do
      post :preview
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :facebook_login, only: [:edit, :update]
end

app/controllers/password_change_controller.rb
class PasswordChangeController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if (@user.authenticate(params[:user][:current_password]) &&
      params[:user][:password] == params[:user][:password_confirmation])
      if params[:user][:password].empty?
        flash.now[:danger] = "パスワードが変更できません"
        render "edit"
      elsif @user.update(user_params)
        flash[:success] = "パスワードを変更しました"
        redirect_to @user
      else
        flash.now[:danger] = "パスワードが変更できません"
        render "edit"
      end
    else
      flash.now[:danger] = "パスワードが変更できません"
      render "edit"
    end
  end
end

private def user_params
  params.require(:user).permit(:password, :password_confirmation)
end

app/views/password_change/edit.html.haml
- provide(:title, "パスワードを変更")
- @header_appear = true
- @footer_appear = true

.edit-area
  .side-bar
    %ul
      %li.side-bar-item
        = link_to "プロフィールを編集", edit_user_path
      %li.side-bar-item.active
        = link_to "パスワードを変更", edit_password_change_path
  .main-edit-area
    = form_with url: password_change_path, scope: :user, method: :patch, local: true do |f|
      -# = render "shared/error_messages", object: f.object
      .image-edit
        .edit-page-avatar
          = render "shared/user_avatar", {user: @user, size: 30}
        .change-image-area
          %p= @user.user_name
      .form-box
        %aside
          = f.label :current_password, "現在のパスワード"
        = f.password_field :current_password, class: "form-control"
      .form-box
        %aside
          = f.label :password, "新しいパスワード"
        = f.password_field :password, class: "form-control"
      .form-box
        %aside
          = f.label :password_confirmation, "新しいパスワードを確認"
        = f.password_field :password_confirmation, class: "form-control"
      
      .form-box
        %aside
        .form-button
          = f.submit "パスワードを変更", class: "btn btn-primary"