config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "likes/:image_id", to: "likes#create", as: :likes
  delete "likes/:image_id", to: "likes#destroy", as: :like
  post "favorites/:image_id", to: "favorites#create", as: :favorites
  delete "favorites/:image_id", to: "favorites#destroy", as: :favorite

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure

  resources :users do
    member do
      get :favorite
      get :following
      get :followers
    end
    collection do
      post :notification
      get :search
    end
  end
  resources :password_change, only: [:edit, :update]
  resources :images, only: [:new, :show, :create, :destroy] do
    collection do
      post :preview
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :facebook_login, only: [:edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images, dependent: :destroy
  has_many :comments, through: :images, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
          foreign_key: "follower_id",
          dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
          foreign_key: "followed_id",
          dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_images, through: :favorites, source: :image
  has_many :notifications, dependent: :destroy
  
  before_save :downcase_email, :downcase_name

  # s3との連携
  has_one_attached :avatar
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
          uniqueness: { case_sensitive: false },
          format: { with: VALID_EMAIL_REGEX }

  validates :full_name, presence: true, length: { maximum: 50 }

  VALID_USER_NAME_AND_PASSWORD_REGEX = /\A\w+\z/
  validates :user_name, presence: true, length: { in: 3..20 },
          uniqueness: { case_sensitive: false },
          format: { with: VALID_USER_NAME_AND_PASSWORD_REGEX }

  has_secure_password
  validates :password, presence: true, length: { in: 6..12 },
          allow_nil: true,
          format: { with: VALID_USER_NAME_AND_PASSWORD_REGEX }

  VALID_URL_REGEX = /\A#{URI::regexp(%w(http https))}\z/
  validates :site_url, allow_nil: true,
          format: { with: VALID_URL_REGEX, allow_blank: true }

  VALID_PHONE_NUMBER_REGEX = /\A(((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|
    \d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}\-?)\d{4}|0120[-(]?\d{3}[-)]?\d{3})\z/x
  validates :phone_num, uniqueness: true, allow_nil: true, allow_blank: true,
          format: { with: VALID_PHONE_NUMBER_REGEX, allow_blank: true }

  enum gender: { man: 1, woman: 2, other: 3 }

  scope :name_search, ->(word) { where("user_name LIKE :word OR full_name LIKE :word", word: "%#{word}%").limit(10) }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # ユーザーのステータスフィードを返す
  def feed
    Image.feeds(id)
  end

  # はじめから６つの写真を返す
  def six_images(image_id)
    Image.six_images(id, image_id)
  end

  # はじめから１０個の通知を返す
  def five_notifications
    Notification.five_notifications(id)
  end

  # ユーザーが通知を見たかどうかを返す
  def unchecked_notifications?
    notifications.where(checked: false).any?
  end

  # ユーザーがいいねしているか返す
  def liked?(image)
    likes.exists?(image_id: image.id)
  end

  # ユーザーがお気に入りにしているか返す
  def favorited?(image)
    favorites.exists?(image_id: image.id)
  end

  # facebookログインに関するメソッド
  def self.from_omniauth(auth)
    user = User.where('email = ?', auth.info.email).first
    if user.blank?
       user = User.new
    end
    user.uid = auth.uid
    user.full_name = auth.info.name
    user.email = auth.info.email
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user
  end

  # メールアドレスを全て小文字にする
  private def downcase_email
    email.downcase! if email.present?
  end

  # 名前を全て小文字にする
  private def downcase_name
    user_name.downcase! if user_name.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [
    :index, :show, :edit, :update, :destroy, :favorite, :following, :followers
  ]
  before_action :correct_user, only: [:edit, :update, :destroy, :favorite]

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @images = @user.images
    @favorites = current_user.favorited_images
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ようこそ#{@user.full_name}さん"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      if avatar = params[:user][:avatar]
        @user.avatar.attach(avatar)
      end
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_url
  end

  def favorite
    @user = User.find(params[:id])
    @favorites = @user.favorited_images
  end

  def notification
    if @notifications = current_user.notifications
      @notifications.each do |notification|
        notification.update(checked: true)
      end
    end
  end

  def search
    word = params[:word]
    @results = search_user(word)
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(5)
  end

  def following
    @user = User.find(params[:id])
    @following = @user.following.page(params[:page]).per(5)
  end

  def facebook_login
    @user = User.from_omniauth(request.env["omniauth.auth"])
    result = @user.save(validate: false)
    if result
      log_in @user
      if @user.user_name.blank?
        redirect_to edit_facebook_login_path(@user)
      else
        redirect_to @user
      end
    else
      redirect_to auth_failure_path
    end
  end

  #認証に失敗した際の処理
  def auth_failure
    @user = User.new
    redirect_to root_url
  end

  private def user_params
    params.require(:user).permit(:email, :full_name,
            :user_name, :password, :password_confirmation,
            :site_url, :introduction, :phone_num,
            :gender)
  end

  # ユーザーネームかフルネームからユーザーを検索する(10人まで)
  private def search_user(word)
    User.name_search(word)
  end
end

app/views/users/_favorite_images.html.haml
%ol
  - images.each do |image|
    .show-posted-image-wrapper
      %li.show-posted-image
        = image_tag image.post_image.variant(resize_to_fill: [300, 300]).processed, alt: "投稿された画像"
        = render "shared/image_modal", image: image

app/views/users/_posted_images.html.haml
%ol
  .row
    - images.each.with_index do |image, idx|
      .col-lg-4.col-6{ id: "image-#{image.id}"}
        .show-posted-image-wrapper
          %li.show-posted-image
            = image_tag image.post_image.variant(resize_to_fill: [300, 300]).processed, alt: "投稿された画像"
            = render "shared/image_modal", image: image
          - if current_user == user
            = link_to image_path(image.id, user_id: user.id), id: "posted-image-delete-#{image.id}",
              class: "image-delete-button", method: :delete,
              data: { confirm: "本当に削除しますか？",title: "確認",
              cancel: "キャンセル", commit: "削除", remote: true } do
              %i.fas.fa-times
      - if idx % 3 == 2 && idx != 0
        .w-100.d-none.d-xl-block

app/views/users/edit.html.haml
- provide(:title, "プロフィールを編集")
- @header_appear = true
- @footer_appear = true

.edit-area
  .side-bar
    %ul
      %li.side-bar-item.active
        = link_to "プロフィールを編集", edit_user_path(current_user)
      %li.side-bar-item
        = link_to "パスワードを変更", edit_password_change_path(current_user)
  .main-edit-area
    = form_with model: @user, local: true do |f|
      = render "shared/error_messages", object: f.object
      .image-edit
        .edit-page-avatar
          = render "shared/user_avatar", {user: @user, size: 100}
        .change-image-area
          %p= @user.user_name
          = f.label :avatar, class: "form-image" do
            %p プロフィール写真を変更
            = f.file_field :avatar, accept: "image/png, image/jpeg"
      .form-box
        %aside
          = f.label :full_name, "名前"
        = f.text_field :full_name, class: "form-control"
      .form-box
        %aside
          = f.label :user_name, "ユーザーネーム"
        = f.text_field :user_name, class: "form-control"
      .form-box
        %aside
          = f.label :site_url, "ウェブサイト"
        = f.url_field :site_url, class: "form-control"
      .form-box
        %aside
          = f.label :introduction, "自己紹介"
        = f.text_area :introduction, class: "form-control"
      .form-box
        %aside
          = f.label :email, "メールアドレス"
        = f.email_field :email, class: "form-control"
      .form-box
        %aside
          = f.label :phone_num, "電話番号"
        = f.telephone_field :phone_num, class: "form-control"
      .form-box
        %aside
          = f.label :gender, "性別"
        .form-control
          = f.label :gender, "男性"
          = f.radio_button :gender, 1
          = f.label :gender, "女性"
          = f.radio_button :gender, 2
          = f.label :gender, "その他"
          = f.radio_button :gender, 3

      .form-box
        %aside
        .form-button
          = f.submit "送信する", class: "btn btn-primary"
          = link_to "アカウントを削除する", user_path, method: :delete, 
                  data: { confirm: "本当に削除しますか？",title: "確認",
                  cancel: "キャンセル", commit: "削除", remote: true }

app/views/users/favorite.html.haml
- provide(:title, "#{@user.full_name}(#{@user.user_name})")
- @header_appear = true
- @footer_appear = true

.fixed

.user-show
  = render "shared/user_avatar", {user: @user, size: 150}
  .user-info
    .user-header
      %h1= @user.user_name
      - if current_user == @user
        .profile-edit-link
          = link_to "プロフィールを編集", edit_user_path(@user)
      - else 
        = render "shared/follow_form", user: @user
    .user-data
      %ul
        %li#post-image-count= "投稿#{@user.images.count}件"
        %li#followers= "フォロワー#{@user.followers.count}人"
        %li#following= "フォロー中#{@user.following.count}人"
    %h3= @user.full_name
    .introduction
      = link_to "#{@user.site_url}", @user.site_url
      %p= @user.introduction
%hr/
.post-image-area
  .post-image-header
    .post-image-nav
      = link_to "投稿", user_path(@user), class: "images-nav-button"
      - if current_user
        = link_to "お気に入り", favorite_user_path(@user), class: "images-nav-button show-page-active"
  = render "favorite_images", {images: @favorites, user: current_user}

app/views/users/followers.js.erb
document.getElementById("followers-modal").innerHTML =
  "<%= j(render("layouts/followers_modal", followers: @followers, user: @user)) %>";

app/views/users/following.js.erb
document.getElementById("following-modal").innerHTML =
  "<%= j(render("layouts/following_modal", following: @following, user: @user)) %>";

app/views/users/index.html.haml
- provide(:title, "一覧")
- @header_appear = true

- @users.each do |user|
  = link_to "#{user.user_name}", user_path(user.id)
  %hr/

app/views/users/new.html.haml
- provide(:title, "登録")
- @footer_appear = true

.create_user
  .form
    = form_with model: @user, url: signup_path, local: true do |f|
      = f.email_field :email, placeholder: "メールアドレス", class: "form-control"
      = f.text_field :full_name, placeholder: "フルネーム", class: "form-control"
      = f.text_field :user_name, placeholder: "ユーザーネーム", class: "form-control"
      = f.password_field :password, placeholder: "パスワード", class: "form-control"
      = f.password_field :password_confirmation, placeholder: "パスワードの確認", class: "form-control"

      = f.submit "登録する", class: "btn btn-primary"
      = render "shared/error_messages", object: f.object
      = link_to "ログインする", root_path
      - terms_link = link_to "利用規約", "#"
      %p 登録することで、#{terms_link}に同意することとします。

app/views/users/notification.js.erb
document.getElementById("red-point-area").innerHTML = "<%= j(render('layouts/red_point')) %>";

app/views/users/search.js.erb
document.getElementById("search-results-area").innerHTML =
  "<%= j(render("layouts/search_results", results: @results)) %>";

app/views/users/show.html.haml
- provide(:title, "#{@user.full_name}(#{@user.user_name})")
- @header_appear = true
- @footer_appear = true

.fixed

.user-show
  = render "shared/user_avatar", {user: @user, size: 150}
  .user-info
    .user-header
      %h1= @user.user_name
      - if current_user == @user
        .profile-edit-link
          = link_to "プロフィールを編集", edit_user_path(@user)
      - else
        = render "shared/follow_form", user: @user
    .user-data
      %ul
        %li#post-image-count= "投稿#{@user.images.count}件"
        %li#followers{ data: { request_url: followers_user_path(@user) } }
          = "フォロワー#{@user.followers.count}人"
        %li#following{ data: { request_url: following_user_path(@user) } }
          = "フォロー中#{@user.following.count}人"
    %h3= @user.full_name
    .introduction
      = link_to "#{@user.site_url}", @user.site_url
      %p= @user.introduction
%hr/
.post-image-area
  .post-image-header
    .post-image-nav
      = link_to "投稿", user_path(@user), class: "images-nav-button show-page-active"
      - if current_user
        = link_to "お気に入り", favorite_user_path(@user), class: "images-nav-button"
  = render "posted_images", {images: @images, user: @user}