config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "likes/:image_id", to: "likes#create", as: :likes
  delete "likes/:image_id", to: "likes#destroy", as: :like
  post "favorites/:image_id", to: "favorites#create", as: :favorites
  delete "favorites/:image_id", to: "favorites#destroy", as: :favorite

  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure

  resources :users do
    member do
      get :favorite
      get :following
      get :followers
    end
    collection do
      post :notification
      get :search
    end
  end
  resources :password_change, only: [:edit, :update]
  resources :images, only: [:new, :show, :create, :destroy] do
    collection do
      post :preview
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :facebook_login, only: [:edit, :update]
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .error_explanation
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_favorite_button.html.haml
- if current_user.favorited?(image)
  = link_to favorite_path(image), method: :delete, remote: true, class: "destroy-favorite" do
    %i.fas.fa-bookmark
- else
  = link_to favorites_path(image), method: :post, remote: true, class: "create-favorite" do
    %i.far.fa-bookmark

app/views/shared/_feed_comments.html.haml
- comments.each do |comment|
  - if avatar_appear
    .image-modal-comment-user-area
      .image-modal-comment-avatar
        = render "shared/user_avatar", {user: User.find(comment.user_id), size: 30}
      %p.image-modal-comment-user-name= User.find(comment.user_id).user_name
    %p.image-modal-comment-sentence= comment.comment
  - else
    %p.posted-comment-user-name= User.find(comment.user_id).user_name
    %p.posted-comment-sentence= comment.comment

app/views/shared/_follow.html.haml
= form_with model: current_user.active_relationships.build, remote: true do |f|
  = hidden_field_tag :followed_id, @user.id
  = f.submit "フォローする", class: "btn btn-primary"

app/views/shared/_follow_form.html.haml
#follow-form
  - if current_user.following?(user)
    = render "shared/unfollow"
  - else
    = render "shared/follow"

app/views/shared/_image_modal.html.haml
.show-page-modal
  = image_tag image.post_image.variant(resize_to_fill: [600, 600]).processed, alt: "投稿された画像"
  %aside
    .image-modal-header
      .image-modal-header-avatar
        = render "shared/user_avatar", {user: image.user, size: 40}
      %p= image.user.user_name
      - unless current_user == image.user
        .image-modal-follow-button
          = render "shared/follow_form", user: image.user
    .image-modal-show-wrapper
      .image-modal-comment-show{ id: "feed-image-#{image.id}" }
        = render "shared/feed_comments", {comments: image.comments, avatar_appear: true}
    .image-modal-icon-area
      .like-button{ id: "like-button-#{image.id}" }
        = render "shared/like_button", image: image
      = link_to image_path(image), class: "image-show-link" do
        %i.far.fa-comment
      .favorite-button.image-modal-favorite{ id: "favorite-button-#{image.id}" }
        = render "shared/favorite_button", image: image
    %p.image-modal-likes-count{ id: "likes-count-#{image.id}" }= "#{image.likes.count}人が「いいね！」しました"
    .image-modal-comment-area
      = form_with model: image.comments.build, remote: true, class: "input-group" do |f|
        = f.text_area :comment, class: "image-modal-post-comment-area", placeholder: "コメントを追加…", rows: "1", id: "comment-#{image.id}"
        = f.hidden_field :image_id, value: image.id
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :state, value: "modal"
        .image-modal-input-group-append
          = f.submit "投稿する", class: "btn"
        

app/views/shared/_like_button.html.haml
- if current_user.liked?(image)
  = link_to like_path(image), method: :delete, remote: true, class: "destroy-like" do
    %i.fas.fa-heart
- else
  = link_to likes_path(image), method: :post, remote: true, class: "create-like" do
    %i.far.fa-heart

app/views/shared/_unfollow.html.haml
= form_with model: current_user.active_relationships.find_by(followed_id: @user.id), method: :delete, remote: true do |f|
  = f.submit "フォローをやめる", class: "btn btn-secondary"

app/views/shared/_user_avatar.html.haml
- if user.avatar.attached?
  = image_tag user.avatar.variant(resize_to_fill: [size, size]).processed,
    alt: user.user_name, class: "user-avatar"
- else
  = image_tag "default_avatar.jpg", alt: user.user_name, height: size, width: size, class: "user-avatar"